# Generated by Django 4.1.2 on 2022-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_profesor_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(related_name='profesor_curso', to='AppCoder.curso'),
        ),
    ]
